name: Parking P+R Monitor 

on:
  repository_dispatch:
    types: [trigger]
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Warsaw
    permissions:
      contents: write

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Download requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Playwright
        run: |
          python -m playwright install chromium --with-deps

      - name: Run
        run: python scraper.py
   

      - name: Save
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add db_parking.db csv_parking.csv
          git commit -m "Update $(date)" || echo "No changes"
          git push
